export const UPDATE_DICTIONARY = 'UPDATE_DICTIONARY';

export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';

export const UPDATE_SCALE_INFO = 'UPDATE_SCALE_INFO';

export const UPDATE_LAST_OPERATION_TIME = 'UPDATE_LAST_OPERATION_TIME';

export const UPDATE_SUBJECT_ID = 'UPDATE_SUBJECT_ID';

export const UPDATE_HOSPITAL_TYPE = 'UPDATE_HOSPITAL_TYPE';

export const PERMIT_DISPLAYING_SENSITIVE_INFO = 'PERMIT_DISPLAYING_SENSITIVE_INFO';

export const DISCARD_RIGHT_OF_DISPLAYING_SENSITIVE_INFO = 'DISCARD_RIGHT_OF_DISPLAYING_SENSITIVE_INFO';

export const SHOW_SENSITIVE_INFO = 'SHOW_SENSITIVE_INFO';

export const HIDE_SENSITIVE_INFO = 'HIDE_SENSITIVE_INFO';

export const UPDATE_LIST_TYPE = 'UPDATE_LIST_TYPE';
