export const UPDATE_DICTIONARY = 'UPDATE_DICTIONARY';

export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';

export const UPDATE_SCALE_INFO = 'UPDATE_SCALE_INFO';

export const UPDATE_LAST_OPERATION_TIME = 'UPDATE_LAST_OPERATION_TIME';

export const UPDATE_SUBJECT_ID = 'UPDATE_SUBJECT_ID';
